self.addEventListener("install",e=>{
  e.waitUntil(
    caches.open("fastmost").then(c=>c.addAll([
      "index.html",
      "voice-lobby.html",
      "chat.html",
      "voice.html",
      "admin.html"
    ]))
  );
});
