app = "fastmost"
primary_region = "ams"

[env]
  PORT = "3000"

[[mounts]]
  source = "data"
  destination = "/app"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
